# Apps.
#
# A package declares apps in its Project.toml:
#
#     [apps]
#     myapp = { submodule = "CLI", julia_flags = ["-q"] }
#
# and provides an entry point via `@main` (run with `julia -m Pkg[.Sub]`).
# Installing creates a per-package environment under
# `<depot>/environments/apps/<PkgName>/`, records everything in the global
# `<depot>/environments/apps/AppManifest.toml` (an ordinary manifest whose
# entries carry the `apps` tables), and writes shims into `<depot>/bin/`.
#
# Shims self-locate their depot (so a moved depot keeps working), pin the
# installing julia by absolute path, and honor `JULIA_APPS_JULIA_CMD` as an
# override. All mutating operations run under a pidlock.
#
# Shim-format bumps reach already-installed apps via `migrate_shims!`, run at
# the start of every mutating operation: it version-checks each installed shim
# and rewrites the stale ones straight from the recorded manifest (no
# reinstall).

module AppsOps

using Base: UUID
using FileWatching: mkpidlock

using ..Errors: pkgerror
using ..Utils: stderr_f
using ..EnvFiles
using ..EnvFiles: ManifestEntry, PathTracked, AppInfo, with_manifest, with_entry,
    entry_path, projectfile_path
using ..Depots: DepotStack, depots1, environments_dir, bin_dir
using ..Configs: Config
using ..Registries: RegistryInstance
using ..Environments
using ..Planning
using ..Planning: PackageRequest
using ..Execution
using ..Utils: printpkgstyle, pathrepr

export app_add, app_develop, app_rm, app_update, app_status

const SHIM_VERSION = "1.1"

apps_dir(d::DepotStack) = joinpath(environments_dir(depots1(d)), "apps")
app_manifest_file(d::DepotStack) = joinpath(apps_dir(d), "AppManifest.toml")

read_app_manifest(d::DepotStack) = read_manifest(app_manifest_file(d))

function write_app_manifest(d::DepotStack, manifest::Manifest)
    mkpath(apps_dir(d))
    return write_manifest(manifest, app_manifest_file(d))
end

app_lock(f, d::DepotStack) = mkpidlock(f, joinpath(mkpath(apps_dir(d)), ".pid"); stale_age = 10)

#########
# Shims #
#########

function shim_path(d::DepotStack, app_name::String)
    return joinpath(bin_dir(depots1(d)), Sys.iswindows() ? app_name * ".bat" : app_name)
end

# Shims self-locate the depot when the script still lives in `<depot>/bin`,
# otherwise fall back to the install-time depot; the app environment is
# addressed depot-relative so relocated depots keep working. Argument
# protocol (Pkg parity): args before a `--` go to julia, args after it to
# the app; without `--` everything goes to the app.
function shim_contents(
        app::AppInfo, depot::String, load_path::String;
        relative_load_path::Bool, windows::Bool = Sys.iswindows(),
    )
    julia = something(app.julia_command, joinpath(Sys.BINDIR, "julia"))
    entry = app.submodule === nothing ? app.name : app.submodule
    return windows ? bat_shim(app, julia, entry, depot, load_path; relative_load_path) :
        sh_shim(app, julia, entry, depot, load_path; relative_load_path)
end

function sh_shim(app::AppInfo, julia::String, entry::String, depot::String, load_path::String; relative_load_path::Bool)
    julia_escaped = Base.shell_escape(julia)
    entry_escaped = Base.shell_escape(entry)
    flags_part = isempty(app.julia_flags) ? "" : " " * join(Base.shell_escape.(app.julia_flags), " ")
    lp = relative_load_path ? "\"\$DEPOT/$load_path\"" : Base.shell_escape(load_path)
    return """
    #!/bin/sh
    set -eu
    # generated by VibePkg (shim version $SHIM_VERSION); do not edit
    SCRIPT_DIR=\$(CDPATH= cd -- "\$(dirname -- "\$0")" && pwd -P)
    if [ -f "\$SCRIPT_DIR/../environments/apps/AppManifest.toml" ]; then
        DEPOT=\$(cd -- "\$SCRIPT_DIR/.." >/dev/null 2>&1 && pwd -P)
    else
        DEPOT=$(Base.shell_escape(depot))
    fi
    JULIA=\${JULIA_APPS_JULIA_CMD:-$julia_escaped}
    export JULIA_DEPOT_PATH="\$DEPOT:"
    export JULIA_LOAD_PATH=$lp

    # `--` splits julia args (before) from app args (after); with no `--`
    # every argument goes to the app. Rebuild "\$@" in place as
    # <julia args> -m <module> <app args>, preserving argument boundaries.
    orig_count=\$#
    seen_sep=false
    i=0
    while [ "\$i" -lt "\$orig_count" ]; do
        arg=\$1
        shift
        if [ "\$seen_sep" = false ] && [ "\$arg" = "--" ]; then
            seen_sep=true
            set -- "\$@" -m $entry_escaped
        else
            set -- "\$@" "\$arg"
        fi
        i=\$((i + 1))
    done
    if [ "\$seen_sep" = false ]; then
        set -- -m $entry_escaped "\$@"
    fi

    exec "\$JULIA" --startup-file=no$flags_part "\$@"
    """
end

function bat_shim(app::AppInfo, julia::String, entry::String, depot::String, load_path::String; relative_load_path::Bool)
    julia_escaped = "\"$(Base.shell_escape_wincmd(julia))\""
    entry_escaped = "\"$(Base.shell_escape_wincmd(entry))\""
    flags_part = isempty(app.julia_flags) ? "" : " " * join(Base.shell_escape_wincmd.(app.julia_flags), " ")
    lp = relative_load_path ? "%depot%\\$(join(splitpath(load_path), '\\'))" : normpath(load_path)
    return """
    @echo off
    setlocal EnableExtensions DisableDelayedExpansion

    rem generated by VibePkg (shim version $SHIM_VERSION); do not edit

    rem Locate the depot from this script (<depot>\\bin\\<app>.bat) so a
    rem relocated depot keeps working; fall back to the install-time depot
    for %%I in ("%~dp0..") do set "depot=%%~fI"
    if not exist "%depot%\\environments\\apps\\AppManifest.toml" set "depot=$(normpath(depot))"

    rem (no delayed expansion here so '!' stays literal; trailing ';' keeps
    rem the default system depots)
    set "JULIA_LOAD_PATH=$lp"
    set "JULIA_DEPOT_PATH=%depot%;"

    if defined JULIA_APPS_JULIA_CMD (
        set "julia_cmd=%JULIA_APPS_JULIA_CMD%"
    ) else (
        set "julia_cmd=$julia_escaped"
    )

    setlocal EnableDelayedExpansion

    rem Parse arguments, splitting on the first -- into julia_args / app_args
    set "found_sep="
    set "julia_args="
    set "app_args="

    :__next
    if "%~1"=="" goto __done

    if not defined found_sep if "%~1"=="--" (
        set "found_sep=1"
        shift
        goto __next
    )

    if not defined found_sep (
        if defined julia_args (
            set "julia_args=!julia_args! %1"
        ) else (
            set "julia_args=%1"
        )
        shift
        goto __next
    )

    if defined found_sep (
        if defined app_args (
            set "app_args=!app_args! %1"
        ) else (
            set "app_args=%1"
        )
        shift
        goto __next
    )

    :__done
    rem With no -- every original argument goes to the app
    if defined found_sep (
        "%julia_cmd%" ^
            --startup-file=no$flags_part !julia_args! ^
            -m $entry_escaped ^
            !app_args!
    ) else (
        "%julia_cmd%" ^
            --startup-file=no$flags_part ^
            -m $entry_escaped ^
            %*
    )
    """
end

function write_shim(d::DepotStack, app::AppInfo, load_path::String; relative_load_path::Bool)
    mkpath(bin_dir(depots1(d)))
    path = shim_path(d, app.name)
    content = shim_contents(app, depots1(d), load_path; relative_load_path)
    if Sys.iswindows()
        # batch files need CRLF line endings for reliable label parsing
        content = replace(replace(content, "\r\n" => "\n"), "\n" => "\r\n")
        write(path, content)
    else
        write(path, content)
        chmod(path, 0o755)
    end
    return path
end

# The shim format version embedded in an installed shim, or `nothing` if the
# file is absent or not a VibePkg-generated shim.
function installed_shim_version(path::String)
    isfile(path) || return nothing
    m = match(r"shim version ([0-9.]+)", read(path, String))
    return m === nothing ? nothing : String(m.captures[1]::SubString{String})
end

# Regenerate the shim for one recorded app from its manifest entry, matching
# the load-path form the original install used: registry-tracked apps get the
# depot-relative path, path-tracked (develop) apps their absolute source.
function rewrite_shim(d::DepotStack, entry::ManifestEntry, app::AppInfo)
    path = entry_path(entry)
    return path === nothing ?
        write_shim(d, app, "environments/apps/$(entry.name)"; relative_load_path = true) :
        write_shim(d, app, path; relative_load_path = false)
end

# Bring already-installed shims up to the current `SHIM_VERSION` without a
# re-add: rewrite every existing shim whose embedded version is stale, purely
# from the recorded manifest. Called at the start of the mutating operations.
function migrate_shims!(d::DepotStack; io::IO = stderr_f())
    isfile(app_manifest_file(d)) || return nothing
    migrated = 0
    for (uuid, entry) in read_app_manifest(d)
        for app in values(entry.apps)
            shim = shim_path(d, app.name)
            isfile(shim) || continue                       # only upgrade existing shims
            installed_shim_version(shim) == SHIM_VERSION && continue
            rewrite_shim(d, entry, app)
            migrated += 1
        end
    end
    migrated == 0 ||
        printpkgstyle(io, :Updated, "$migrated app shim$(migrated == 1 ? "" : "s") to format v$SHIM_VERSION", color = Base.info_color())
    return nothing
end

#################
# App discovery #
#################

# The apps a package tree declares, with the entry-point module names
# resolved (`Pkg` or `Pkg.Submodule`).
function declared_apps(pkg_root::String, pkg_name::String)
    project = read_project(projectfile_path(pkg_root))
    apps = Dict{String, AppInfo}()
    for (app_name, info) in project.apps
        submodule = info.submodule === nothing ? pkg_name : "$pkg_name.$(info.submodule)"
        apps[app_name] = AppInfo(
            app_name, joinpath(Sys.BINDIR, "julia"), submodule,
            info.julia_flags, Dict{String, Any}(),
        )
    end
    isempty(apps) && pkgerror("package `$pkg_name` at `$pkg_root` does not declare any apps (no `[apps]` section)")
    return apps
end

function validate_app_collisions(manifest::Manifest, uuid::UUID, apps::Dict{String, AppInfo})
    for (other_uuid, entry) in manifest
        other_uuid == uuid && continue
        collisions = sort!(collect(intersect(keys(apps), keys(entry.apps))))
        isempty(collisions) && continue
        noun = length(collisions) == 1 ? "app name" : "app names"
        pkgerror(
            "$noun $(join(repr.(collisions), ", ")) already installed by package `$(entry.name)`"
        )
    end
    return nothing
end

function remove_or_restore_shim!(d::DepotStack, manifest::Manifest, app_name::String)
    for (_, entry) in manifest
        app = get(entry.apps, app_name, nothing)
        app === nothing || return rewrite_shim(d, entry, app)
    end
    Base.rm(shim_path(d, app_name); force = true)
    return nothing
end

function record_app_package!(d::DepotStack, entry::ManifestEntry)
    manifest = read_app_manifest(d)
    validate_app_collisions(manifest, entry.uuid, entry.apps)
    previous = get(manifest, entry.uuid, nothing)
    deps = Dict{UUID, ManifestEntry}(manifest.deps)
    deps[entry.uuid] = entry
    updated = with_manifest(manifest; deps, julia_version = VERSION)
    write_app_manifest(d, updated)
    if previous !== nothing
        for app_name in setdiff(keys(previous.apps), keys(entry.apps))
            remove_or_restore_shim!(d, updated, app_name)
        end
    end
    return nothing
end

function replace_app_environment!(staging::String, destination::String)
    backup = nothing
    if ispath(destination)
        backup = tempname(dirname(destination))
        mv(destination, backup)
    end
    try
        mv(staging, destination)
    catch
        if backup !== nothing && ispath(backup)
            Base.rm(destination; force = true, recursive = true)
            mv(backup, destination)
        end
        rethrow()
    end
    backup === nothing || Base.rm(backup; force = true, recursive = true)
    return nothing
end

function print_path_hint(d::DepotStack, io::IO)
    bindir = bin_dir(depots1(d))
    if !occursin(bindir, get(ENV, "PATH", ""))
        printpkgstyle(io, :Info, "add $(pathrepr(bindir)) to your PATH to run the installed apps", color = Base.info_color())
    end
    return
end

##############
# Operations #
##############

"""
    app_develop(config, registries, path; io)

Track the package at `path` as an app source: its own environment is
instantiated in place and the shims point straight at it.
"""
function app_develop(config::Config, registries::Vector{RegistryInstance}, path::String; io::IO = stderr_f())
    d = config.depots
    return app_lock(d) do
        migrate_shims!(d; io)
        dev_dir = abspath(path)
        project_file = projectfile_path(dev_dir; strict = true)
        project_file === nothing && pkgerror("could not find project file in package at `$path`")
        project = read_project(project_file)
        (project.name === nothing || project.uuid === nothing) &&
            pkgerror("expected a `name` and `uuid` entry in project file at `$project_file`")
        apps = declared_apps(dev_dir, project.name)
        validate_app_collisions(read_app_manifest(d), project.uuid, apps)

        # make the dev'd project itself loadable
        env = Environments.load_environment_from(project_file; depots = d)
        planned = plan_resolve(env, registries, config)
        Execution.apply!(env, planned, registries, config; io)

        entry = ManifestEntry(
            project.name, project.uuid, PathTracked(dev_dir, project.version), false,
            Dict{String, UUID}(), Dict{String, UUID}(),
            Dict{String, Union{String, Vector{String}}}(), apps,
            nothing, nothing, Dict{String, Any}(),
        )
        record_app_package!(d, entry)
        for app in values(apps)
            write_shim(d, app, dev_dir; relative_load_path = false)
            printpkgstyle(io, :Installed, "app `$(app.name)`")
        end
        print_path_hint(d, io)
        nothing
    end
end

"""
    app_add(config, registries, request; io)

Install a registered package as an app: a dedicated environment under
`environments/apps/<Name>/` is resolved and instantiated, and shims are
written for every app the package declares.
"""
function app_add(config::Config, registries::Vector{RegistryInstance}, request::PackageRequest; io::IO = stderr_f())
    d = config.depots
    return app_lock(d) do
        migrate_shims!(d; io)
        # resolve the request up-front (against an empty environment, so
        # purely from registries/stdlibs): the environment directory and the
        # shim load path must use the same name, also for uuid-only requests
        name, uuid = Planning.resolve_request(
            Environments.load_environment_from(joinpath(apps_dir(d), "Project.toml"); depots = d),
            registries, request,
        )
        # Build the per-package environment off to the side. A failed resolve,
        # download, or metadata check must leave the currently installed app
        # runnable.
        env_dir = joinpath(apps_dir(d), name)
        entry, apps = mktempdir(apps_dir(d); prefix = ".install-") do staging
            env = Environments.load_environment_from(joinpath(staging, "Project.toml"); depots = d)
            planned = plan_add(env, registries, config, [request])
            result = Execution.apply!(env, planned, registries, config; io)
            entry = result.env.manifest[uuid]
            source = Execution.entry_source_path(result.env.manifest_file, entry, d)
            apps = declared_apps(source, name)
            validate_app_collisions(read_app_manifest(d), uuid, apps)
            replace_app_environment!(staging, env_dir)
            (entry, apps)
        end
        record_app_package!(d, with_entry(entry; apps))
        for app in values(apps)
            # depot-relative load path keeps relocated depots working
            write_shim(d, app, "environments/apps/$name"; relative_load_path = true)
            printpkgstyle(io, :Installed, "app `$(app.name)`")
        end
        print_path_hint(d, io)
        nothing
    end
end

"""
    app_rm(depots, name; io)

Remove by package name (all its apps, its environment, its entry) or by app
name (that app from every package, dropping packages left appless).
"""
function app_rm(d::DepotStack, name::String; io::IO = stderr_f())
    return app_lock(d) do
        manifest = read_app_manifest(d)
        deps = Dict{UUID, ManifestEntry}(manifest.deps)
        removed_apps = String[]
        removed_pkgs = UUID[]
        for (uuid, entry) in deps
            if entry.name == name
                append!(removed_apps, keys(entry.apps))
                push!(removed_pkgs, uuid)
            elseif haskey(entry.apps, name)
                push!(removed_apps, name)
                apps = Dict{String, AppInfo}(entry.apps)
                delete!(apps, name)
                if isempty(apps)
                    push!(removed_pkgs, uuid)
                else
                    deps[uuid] = with_entry(entry; apps)
                end
            end
        end
        isempty(removed_apps) && isempty(removed_pkgs) &&
            pkgerror("no app or app-providing package named `$name` is installed")
        for uuid in removed_pkgs
            entry = deps[uuid]
            entry_path(entry) === nothing && Base.rm(joinpath(apps_dir(d), entry.name); force = true, recursive = true)
            delete!(deps, uuid)
        end
        write_app_manifest(d, with_manifest(manifest; deps))
        for app in unique!(removed_apps)
            remove_or_restore_shim!(d, with_manifest(manifest; deps), app)
            printpkgstyle(io, :Removed, "app `$app`")
        end
        nothing
    end
end

"""
    app_update(config, registries, [name]; io)

Update installed apps: registry-tracked app packages are reinstalled at
their latest resolvable version, path-tracked ones re-resolve in place;
shims are rewritten either way. `name` (a package or app name) restricts
the update; with no name every installed app updates.
"""
function app_update(
        config::Config, registries::Vector{RegistryInstance},
        name::Union{Nothing, String} = nothing; io::IO = stderr_f(),
    )
    d = config.depots
    manifest = read_app_manifest(d)
    targets = ManifestEntry[]
    for (uuid, entry) in manifest
        if name === nothing || entry.name == name || haskey(entry.apps, name)
            push!(targets, entry)
        end
    end
    if isempty(targets)
        name === nothing ||
            pkgerror("no app or app-providing package named `$name` is installed")
        printpkgstyle(io, :Info, "no apps installed", color = Base.info_color())
        return nothing
    end
    # app_add/app_develop take the app lock themselves, so no lock here
    for entry in targets
        path = entry_path(entry)
        if path !== nothing
            app_develop(config, registries, path; io)
        else
            app_add(config, registries, PackageRequest(entry.name, entry.uuid, nothing); io)
        end
    end
    return nothing
end

"""
    app_status(depots, [filter_names]; io)

List installed app packages and their apps, optionally restricted to the
given package or app names.
"""
function app_status(d::DepotStack, filter_names::Vector{String} = String[]; io::IO = stderr_f())
    manifest = read_app_manifest(d)
    printpkgstyle(io, :Status, pathrepr(app_manifest_file(d)))
    for (uuid, entry) in manifest
        isempty(filter_names) || entry.name in filter_names ||
            any(in(filter_names), keys(entry.apps)) || continue
        v = EnvFiles.entry_version(entry)
        tracking = entry_path(entry) !== nothing ? " `$(entry_path(entry))`" : ""
        println(io, "  [", string(uuid)[1:8], "] ", entry.name, v === nothing ? "" : " v$v", tracking)
        for (app_name, app) in entry.apps
            println(io, "    ", app_name)
        end
    end
    return
end

end # module
